id: C2SEC-Domain Scan
version: -1
name: C2SEC-Domain Scan
description: |
  Launches a C2sec scan by domain name and waits for the scan to finish by polling its status in pre-defined intervals.
starttaskid: "0"
fromversion: "4.0.0"
tasks:
  "0":
    id: "0"
    taskid: dd24da52-41e0-4d4f-8277-54ee703c4edb
    type: start
    task:
      id: dd24da52-41e0-4d4f-8277-54ee703c4edb
      version: -1
      name: ""
      description: start
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 827.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: 5d737dff-3e3a-49be-8bb6-5492d43dedde
    type: regular
    task:
      id: 5d737dff-3e3a-49be-8bb6-5492d43dedde
      version: -1
      name: Scan Request
      description: Scan Request
      script: '|||irisk-rescan-company'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      domain:
        simple: ${inputs.DomainName}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 370
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: 81eb34dd-f8f2-404c-834f-5f7c19a86226
    type: playbook
    task:
      id: 81eb34dd-f8f2-404c-834f-5f7c19a86226
      version: -1
      name: GenericPolling
      description: |-
        Use as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continually running the command in Step #2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      Ids:
        simple: ${C2sec.Scan.workitemid}
      Interval:
        simple: ${inputs.interval}
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: irisk-query-workitem
      Timeout:
        simple: "15"
      dt:
        simple: C2sec.Scan(val.status!='completed').workitemid
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 500,
          "y": 545
        }
      }
    note: false
    timertriggers: []
  "6":
    id: "6"
    taskid: 873f2ed8-75cb-41ce-87e3-f32c2584723c
    type: regular
    task:
      id: 873f2ed8-75cb-41ce-87e3-f32c2584723c
      version: -1
      name: Query Issues
      description: Query Issues
      script: C2sec|||irisk-query-issues
      type: regular
      iscommand: true
      brand: C2sec
    nexttasks:
      '#none#':
      - "8"
      - "10"
      - "13"
    scriptarguments:
      domain:
        simple: ${inputs.DomainName}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 895
        }
      }
    note: true
    timertriggers: []
  "8":
    id: "8"
    taskid: 8bf5f5d7-6b60-45a5-8b4a-7261c0e801db
    type: condition
    task:
      id: 8bf5f5d7-6b60-45a5-8b4a-7261c0e801db
      version: -1
      name: Leaked Credentials Reported?
      description: Leaked Credentials Reported?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: C2sec.Issue.component
            iscontext: true
          right:
            value:
              simple: credential
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
  "9":
    id: "9"
    taskid: d34744c3-0045-4012-8590-d9d942858522
    type: regular
    task:
      id: d34744c3-0045-4012-8590-d9d942858522
      version: -1
      name: Get Leaked Credentials Report
      description: Get Leaked Credentials Report
      script: '|||irisk-query-component'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      component:
        simple: credential
      domain:
        simple: ${inputs.DomainName}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
  "10":
    id: "10"
    taskid: be0b16c8-08b0-40a2-8214-afde40c46430
    type: condition
    task:
      id: be0b16c8-08b0-40a2-8214-afde40c46430
      version: -1
      name: Application Vulnerabilities Reported?
      description: Application Vulnerabilities Reported?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: C2sec.Issue.component
            iscontext: true
          right:
            value:
              simple: application
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
  "11":
    id: "11"
    taskid: 3d43a51e-b63d-4c42-8522-94b3c1147913
    type: regular
    task:
      id: 3d43a51e-b63d-4c42-8522-94b3c1147913
      version: -1
      name: Get Application Vulnerabilities Report
      description: Get Application Vulnerabilities Report
      script: '|||irisk-query-component'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      component:
        simple: application
      domain:
        simple: ${inputs.DomainName}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 612.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
  "13":
    id: "13"
    taskid: 292b4091-037a-4679-85a4-e939ee175af8
    type: regular
    task:
      id: 292b4091-037a-4679-85a4-e939ee175af8
      version: -1
      name: Get Network Services Exposed Report
      description: Get Network Services Exposed Report
      script: '|||irisk-query-component'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      component:
        simple: network
      domain:
        simple: ${inputs.DomainName}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1042.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
  "14":
    id: "14"
    taskid: f5576732-6f4a-49ee-80ec-33bc31372c8b
    type: title
    task:
      id: f5576732-6f4a-49ee-80ec-33bc31372c8b
      version: -1
      name: Done
      description: playbook end
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
  "15":
    id: "15"
    taskid: d4e50d62-c6d9-4825-8551-068ac8741c26
    type: condition
    task:
      id: d4e50d62-c6d9-4825-8551-068ac8741c26
      version: -1
      name: Is C2sec enabled?
      description: checking if the integration is enabled
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: C2sec
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 827.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "16":
    id: "16"
    taskid: 266f91a7-b73f-4ffd-8718-039fd2e8d20f
    type: regular
    task:
      id: 266f91a7-b73f-4ffd-8718-039fd2e8d20f
      version: -1
      name: Query Scan Result
      description: Pulling latest Scan Results from C2sec
      script: '|||irisk-query-workitem'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      id:
        simple: ${C2sec.Scan.workitemid}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 720
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {
      "10_11_yes": 0.55,
      "8_9_yes": 0.53
    },
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 1372.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: DomainName
  value: {}
  required: true
  description: Domain Name
- key: interval
  value:
    simple: "1"
  required: false
  description: Polling frequency - how often the polling command should run (minutes)
- key: timeout
  value:
    simple: "600"
  required: false
  description: How much time to wait before a timeout occurs (minutes)
outputs: []
